name: Automated tests
on:
  push

jobs:
  test:
    runs-on: my-trinkets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest api_test/tests
