name: Automated tests
on:
  push

jobs:
  test:
    runs-on: my-trinkets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        env:
          BOOKING_API_USERNAME: ${{ secrets.BOOKING_API_USERNAME }}
          BOOKING_API_PASSWORD: ${{ secrets.BOOKING_API_PASSWORD }}
        run: pytest booking_api_test/tests
